name: Register Build Artifact

on: [workflow_dispatch]
  
jobs:
  run-register-build-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Register Build Artifact
        id: artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: "artifact-demo-20251003"
          version: 1.0.1
          url: "ghcr.io/haakaashbee/testaction/prod-artifact:latest"
          digest: "sha256:566b1117a16243a43be01e378a20ee823c95d00cd5f3231ad4d168f53d99d9d8"
          type: "docker"
          label: 'QA,preprod'
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"

      - name: Test output
        run: echo '${{ steps.artifact.outputs.cbp_artifact_id }}'
